// Generated by gencpp from file rubber_cone_mission/Fin.msg
// DO NOT EDIT!


#ifndef RUBBER_CONE_MISSION_MESSAGE_FIN_H
#define RUBBER_CONE_MISSION_MESSAGE_FIN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rubber_cone_mission
{
template <class ContainerAllocator>
struct Fin_
{
  typedef Fin_<ContainerAllocator> Type;

  Fin_()
    : num(0)
    , centroid_x()
    , centroid_y()
    , aveD()
    , minD()
    , angle()
    , size()  {
    }
  Fin_(const ContainerAllocator& _alloc)
    : num(0)
    , centroid_x(_alloc)
    , centroid_y(_alloc)
    , aveD(_alloc)
    , minD(_alloc)
    , angle(_alloc)
    , size(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _num_type;
  _num_type num;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _centroid_x_type;
  _centroid_x_type centroid_x;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _centroid_y_type;
  _centroid_y_type centroid_y;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _aveD_type;
  _aveD_type aveD;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _minD_type;
  _minD_type minD;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _angle_type;
  _angle_type angle;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _size_type;
  _size_type size;





  typedef boost::shared_ptr< ::rubber_cone_mission::Fin_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rubber_cone_mission::Fin_<ContainerAllocator> const> ConstPtr;

}; // struct Fin_

typedef ::rubber_cone_mission::Fin_<std::allocator<void> > Fin;

typedef boost::shared_ptr< ::rubber_cone_mission::Fin > FinPtr;
typedef boost::shared_ptr< ::rubber_cone_mission::Fin const> FinConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rubber_cone_mission::Fin_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rubber_cone_mission::Fin_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rubber_cone_mission::Fin_<ContainerAllocator1> & lhs, const ::rubber_cone_mission::Fin_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num &&
    lhs.centroid_x == rhs.centroid_x &&
    lhs.centroid_y == rhs.centroid_y &&
    lhs.aveD == rhs.aveD &&
    lhs.minD == rhs.minD &&
    lhs.angle == rhs.angle &&
    lhs.size == rhs.size;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rubber_cone_mission::Fin_<ContainerAllocator1> & lhs, const ::rubber_cone_mission::Fin_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rubber_cone_mission

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rubber_cone_mission::Fin_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rubber_cone_mission::Fin_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rubber_cone_mission::Fin_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rubber_cone_mission::Fin_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rubber_cone_mission::Fin_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rubber_cone_mission::Fin_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rubber_cone_mission::Fin_<ContainerAllocator> >
{
  static const char* value()
  {
    return "421d0d272a8d8a52e65daee64dcb6ee2";
  }

  static const char* value(const ::rubber_cone_mission::Fin_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x421d0d272a8d8a52ULL;
  static const uint64_t static_value2 = 0xe65daee64dcb6ee2ULL;
};

template<class ContainerAllocator>
struct DataType< ::rubber_cone_mission::Fin_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rubber_cone_mission/Fin";
  }

  static const char* value(const ::rubber_cone_mission::Fin_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rubber_cone_mission::Fin_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 num            # 유효한 클러스터의 개수\n"
"float64[] centroid_x # 유효한 클러스터들의 x 좌표\n"
"float64[] centroid_y # 유효한 클러스터들의 y 좌표\n"
"float64[] aveD    # 각 클러스터의 중심점 x 좌표 리스트\n"
"float64[] minD    # 각 클러스터의 중심점 y 좌표 리스트\n"
"float64[] angle   # 각 클러스터의 각도 (필요한 경우)\n"
"float64[] size    # 각 클러스터의 크기 (필요한 경우)\n"
;
  }

  static const char* value(const ::rubber_cone_mission::Fin_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rubber_cone_mission::Fin_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
      stream.next(m.centroid_x);
      stream.next(m.centroid_y);
      stream.next(m.aveD);
      stream.next(m.minD);
      stream.next(m.angle);
      stream.next(m.size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Fin_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rubber_cone_mission::Fin_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rubber_cone_mission::Fin_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num);
    s << indent << "centroid_x[]" << std::endl;
    for (size_t i = 0; i < v.centroid_x.size(); ++i)
    {
      s << indent << "  centroid_x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.centroid_x[i]);
    }
    s << indent << "centroid_y[]" << std::endl;
    for (size_t i = 0; i < v.centroid_y.size(); ++i)
    {
      s << indent << "  centroid_y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.centroid_y[i]);
    }
    s << indent << "aveD[]" << std::endl;
    for (size_t i = 0; i < v.aveD.size(); ++i)
    {
      s << indent << "  aveD[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.aveD[i]);
    }
    s << indent << "minD[]" << std::endl;
    for (size_t i = 0; i < v.minD.size(); ++i)
    {
      s << indent << "  minD[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.minD[i]);
    }
    s << indent << "angle[]" << std::endl;
    for (size_t i = 0; i < v.angle.size(); ++i)
    {
      s << indent << "  angle[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.angle[i]);
    }
    s << indent << "size[]" << std::endl;
    for (size_t i = 0; i < v.size.size(); ++i)
    {
      s << indent << "  size[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.size[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RUBBER_CONE_MISSION_MESSAGE_FIN_H
